/**
 * Diccionario local de palabras clave — Tecnología y Electrónica.
 * Autodetección instantánea sin IA (solo reglas).
 */

export const TECH_CATEGORY_KEYWORDS: Record<string, string[]> = {
  celulares: [
    "iphone",
    "samsung galaxy",
    "galaxy s",
    "galaxy a",
    "smartphone",
    "celular",
    "movil",
    "móvil",
    "android",
    "redmi",
    "xiaomi",
    "honor",
    "motorola",
    "poco",
    "oppo",
    "vivo",
    "realme",
    "pixel",
    "oneplus",
    "huawei",
    "nokia",
    "tcl",
    "infinix",
    "tecno",
  ],
  laptops: [
    "laptop",
    "notebook",
    "macbook",
    "portatil",
    "portátil",
    "ultrabook",
    "thinkpad",
    "vivobook",
    "ideapad",
    "legion",
    "lenovo",
    "dell",
    "hp",
    "asus",
    "acer",
    "msi",
    "surface",
    "chromebook",
    "computadora",
    "computador",
    "ordenador",
    "pc",
    "desktop",
    "all in one",
    "aio",
    "imac",
    "mac mini",
    "rog strix",
    "nitro 5",
    "pavilion",
    "inspiron",
    "latitude",
    "elitebook",
    "probook",
    "envy",
    "spectre",
    "predator",
    "swift",
    "aspire",
  ],
  tablets: [
    "tablet",
    "ipad",
    "tab s",
    "galaxy tab",
    "fire hd",
    "kindle fire",
    "surface pro",
    "lenovo tab",
  ],
  audio: [
    "audifono",
    "audífono",
    "auricular",
    "headphone",
    "headset",
    "earbud",
    "earbuds",
    "airpods",
    "parlante",
    "speaker",
    "bocina",
    "soundbar",
    "barra de sonido",
    "subwoofer",
    "microfono",
    "micrófono",
    "jbl",
    "bose",
    "sony wh",
  ],
  accesorios: [
    "cargador",
    "adaptador",
    "cable usb",
    "cable hdmi",
    "hub usb",
    "funda",
    "case",
    "protector",
    "mica",
    "mouse",
    "raton",
    "ratón",
    "teclado",
    "keyboard",
    "webcam",
    "pad mouse",
    "base refrigerante",
    "dock",
    "punta de cargador",
    "power bank",
    "bateria externa",
  ],
  repuestos: [
    "repuesto",
    "pantalla lcd",
    "display",
    "bateria",
    "batería",
    "flex",
    "pin de carga",
    "tapa trasera",
    "modulo camara",
    "módulo cámara",
  ],
  procesadores: [
    "procesador",
    "processor",
    "cpu",
    "intel",
    "amd",
    "ryzen",
    "threadripper",
    "pentium",
    "celeron",
    "athlon",
    "core i3",
    "core i5",
    "core i7",
    "core i9",
    "core ultra",
    "xeon",
    "apu",
    "socket am4",
    "socket am5",
    "lga 1700",
    "lga1700",
  ],
  "tarjetas-madre": [
    "tarjeta madre",
    "tarjeta-madre",
    "motherboard",
    "placa madre",
    "placa base",
    "mainboard",
    "mobo",
    "chipset",
    "b450",
    "b550",
    "b650",
    "x570",
    "x670",
    "z690",
    "z790",
    "h610",
    "h770",
  ],
  "memorias-ram": [
    "memoria ram",
    "memorias ram",
    "ram ddr",
    "ddr3",
    "ddr4",
    "ddr5",
    "sodimm",
    "dimm",
    "kingston fury",
    "corsair vengeance",
    "g.skill",
    "gskill",
    "hyperx",
    "ballistix",
  ],
  "almacenamiento-pc": [
    "ssd",
    "nvme",
    "m.2",
    "m2",
    "disco duro",
    "disco duro externo",
    "hdd",
    "sata",
    "wd blue",
    "wd black",
    "samsung evo",
    "crucial",
    "sandisk",
    "kingston ssd",
    "seagate",
    "solid state",
  ],
  "tarjetas-graficas": [
    "tarjeta grafica",
    "tarjeta gráfica",
    "tarjeta de video",
    "gpu",
    "nvidia",
    "geforce",
    "rtx",
    "gtx",
    "radeon",
    "rx 580",
    "rx 6600",
    "rx 6700",
    "rx 7600",
    "quadro",
    "arc a",
    "vram",
  ],
  "fuentes-poder": [
    "fuente de poder",
    "fuente poder",
    "power supply",
    "psu",
    "80 plus",
    "80+",
    "modular",
    "semi modular",
    "evga",
    "cooler master psu",
    "seasonic",
    "corsair rm",
  ],
  gabinetes: [
    "gabinete",
    "case pc",
    "pc case",
    "tower",
    "mid tower",
    "full tower",
    "chassis",
    "gabinete gamer",
  ],
};

/** Menor número = más específico; gana en empates de puntuación. */
export const TECH_CATEGORY_PRIORITY: Record<string, number> = {
  procesadores: 1,
  "tarjetas-madre": 2,
  "memorias-ram": 3,
  "almacenamiento-pc": 4,
  "tarjetas-graficas": 5,
  "fuentes-poder": 6,
  gabinetes: 7,
  repuestos: 8,
  accesorios: 9,
  audio: 10,
  tablets: 11,
  laptops: 12,
  celulares: 13,
};
