/** Diccionario local — Alimentos y Bebidas */

export const ALIMENTOS_CATEGORY_KEYWORDS: Record<string, string[]> = {
  entradas: [
    "entrada",
    "entradas",
    "aperitivo",
    "aperitivos",
    "ensalada",
    "ensaladas",
    "sopa",
    "sopas",
    "crema de",
    "consome",
    "consomé",
    "ceviche",
    "tequeños",
    "tequeño",
    "empanada",
    "empanadas",
    "nachos",
    "guacamole",
    "hummus",
    "croquetas",
    "nuggets",
  ],
  "platos-principales": [
    "plato principal",
    "plato fuerte",
    "arepa",
    "arepas",
    "pasta",
    "espagueti",
    "espaghetti",
    "hamburguesa",
    "hamburguesas",
    "burger",
    "pollo",
    "pechuga",
    "carne",
    "bistec",
    "parrilla",
    "pizza",
    "pizzas",
    "bowl",
    "poke",
    "pabellon",
    "pabellón",
    "asado",
    "pescado",
    "salmon",
    "salmón",
    "arroz",
    "risotto",
    "tacos",
    "burrito",
    "wrap",
    "sandwich",
    "sándwich",
    "hot dog",
    "perro caliente",
  ],
  bebidas: [
    "bebida",
    "bebidas",
    "jugo",
    "jugos",
    "refresco",
    "refrescos",
    "gaseosa",
    "soda",
    "cafe",
    "café",
    "espresso",
    "capuccino",
    "cappuccino",
    "latte",
    "te ",
    "té ",
    "infusion",
    "infusión",
    "smoothie",
    "batido",
    "malta",
    "cerveza",
    "vino",
    "whisky",
    "ron",
    "agua mineral",
    "limonada",
    "chicha",
  ],
  postres: [
    "postre",
    "postres",
    "torta",
    "tortas",
    "pastel",
    "pasteles",
    "cake",
    "helado",
    "helados",
    "brownie",
    "brownies",
    "dulce",
    "dulces",
    "flan",
    "quesillo",
    "tiramisu",
    "tiramisú",
    "galleta",
    "galletas",
    "donut",
    "donas",
    "muffin",
    "cupcake",
    "churros",
  ],
};

export const ALIMENTOS_CATEGORY_PRIORITY: Record<string, number> = {
  entradas: 1,
  "platos-principales": 2,
  bebidas: 3,
  postres: 4,
};
