/** Diccionario local — Coleccionables y Cómics */

export const COLECCIONABLES_CATEGORY_KEYWORDS: Record<string, string[]> = {
  comics: [
    "comic",
    "cómic",
    "comics",
    "manga",
    "graphic novel",
    "novela grafica",
    "novela gráfica",
    "marvel",
    "dc comics",
    "spiderman",
    "spider-man",
    "batman",
    "superman",
    "tomo",
    "vol.",
    "volume",
  ],
  figuras: [
    "figura",
    "figuras",
    "funko",
    "funko pop",
    "action figure",
    "figura de accion",
    "figura de acción",
    "statue",
    "estatua",
    "nendoroid",
    "figuarts",
    "hot toys",
    "model kit",
    "bandai",
    "hasbro",
    "mcfarlane",
    "pop mart",
    "labubu",
  ],
  cartas: [
    "carta",
    "cartas",
    "tcg",
    "trading card",
    "pokemon",
    "pokémon",
    "yugioh",
    "yu-gi-oh",
    "magic the gathering",
    "mtg",
    "one piece card",
    "lorcana",
    "digimon",
    "booster",
    "sobre de cartas",
    "deck",
    "mazo",
  ],
  merch: [
    "merch",
    "merchandising",
    "poster",
    "posters",
    "playera",
    "remera",
    "sudadera",
    "hoodie",
    "pin",
    "pins",
    "llavero",
    "llaveros",
    "taza",
    "mug",
    "peluche",
    "sticker",
    "stickers",
  ],
  otros: [
    "coleccionable",
    "coleccionables",
    "edicion limitada",
    "edición limitada",
    "exclusivo",
  ],
};

export const COLECCIONABLES_CATEGORY_PRIORITY: Record<string, number> = {
  comics: 1,
  figuras: 2,
  cartas: 3,
  merch: 4,
  otros: 5,
};
