/** Diccionario local — Papelería, Librería y Oficina */

export const PAPELERIA_CATEGORY_KEYWORDS: Record<string, string[]> = {
  cuadernos: [
    "cuaderno",
    "cuadernos",
    "libreta",
    "libretas",
    "agenda",
    "agendas",
    "planner",
    "block de notas",
    "bloc de notas",
    "libro de caligrafia",
    "libro de caligrafía",
    "sketchbook",
    "croquera",
  ],
  "utiles-escolares": [
    "lapiz",
    "lápiz",
    "lapices",
    "lápices",
    "boligrafo",
    "bolígrafo",
    "pluma",
    "plumas",
    "marcador",
    "marcadores",
    "resaltador",
    "resaltadores",
    "highlighter",
    "regla",
    "escuadra",
    "transportador",
    "goma",
    "goma de borrar",
    "borrador",
    "sacapuntas",
    "tijeras",
    "colores",
    "crayones",
    "creyones",
    "tempera",
    "acuarela",
    "pincel",
    "pegamento",
    "stick glue",
  ],
  papeleria: [
    "papel",
    "papeles",
    "cartulina",
    "cartulinas",
    "sobre",
    "sobres",
    "folder",
    "folders",
    "carpeta",
    "carpetas",
    "archivador",
    "filing",
    "hoja",
    "hojas sueltas",
    "block",
    "bloc",
  ],
  "material-oficina": [
    "grapa",
    "grapadora",
    "engrapadora",
    "perforadora",
    "sacagrapas",
    "clips",
    "clip",
    "chinches",
    "cinta adhesiva",
    "cinta masking",
    "masking tape",
    "calculadora",
    "organizador",
    "porta documentos",
    "guillotina",
    "cutter",
    "sticky notes",
    "post it",
    "post-it",
  ],
  impresion: [
    "tinta",
    "tintas",
    "toner",
    "toner cartridge",
    "cartucho",
    "cartuchos",
    "resma",
    "resmas",
    "papel bond",
    "papel fotografico",
    "papel fotográfico",
    "filamento",
    "3d filament",
  ],
  libros: [
    "libro",
    "libros",
    "novela",
    "novelas",
    "manual",
    "manuales",
    "texto escolar",
    "textbook",
    "diccionario",
    "enciclopedia",
    "revista",
    "magazine",
  ],
};

export const PAPELERIA_CATEGORY_PRIORITY: Record<string, number> = {
  cuadernos: 1,
  "utiles-escolares": 2,
  impresion: 3,
  papeleria: 4,
  "material-oficina": 5,
  libros: 6,
};
