/** Diccionario local — Ropa, Calzado y Moda */

export const ROPA_MODA_CATEGORY_KEYWORDS: Record<string, string[]> = {
  camisas: [
    "camisa",
    "camiseta",
    "t-shirt",
    "tshirt",
    "playera",
    "remera",
    "polo",
    "blusa",
    "franela",
    "top",
    "musculosa",
    "henley",
    "camibuso",
    "oxford shirt",
  ],
  pantalones: [
    "pantalon",
    "pantalón",
    "jean",
    "jeans",
    "denim",
    "jogger",
    "joggers",
    "short",
    "shorts",
    "bermuda",
    "bermudas",
    "legging",
    "leggings",
    "falda",
    "faldas",
    "cargo",
    "chino",
    "drill",
  ],
  calzado: [
    "calzado",
    "zapato",
    "zapatos",
    "zapatilla",
    "zapatillas",
    "sneaker",
    "sneakers",
    "tenis",
    "bota",
    "botas",
    "sandalia",
    "sandalias",
    "chancleta",
    "mocasin",
    "mocasín",
    "baletas",
    "merceditas",
  ],
  zapatos: [
    "zapato formal",
    "zapatos de vestir",
    "oxford",
    "derby",
    "mocasin",
    "mocasín",
    "loafer",
    "tacon",
    "tacón",
    "stiletto",
    "pumps",
  ],
  botas: [
    "bota",
    "botas",
    "botin",
    "botín",
    "botines",
    "timberland",
    "chelsea boot",
    "caña alta",
    "work boot",
  ],
  sandalias: [
    "sandalia",
    "sandalias",
    "chancleta",
    "chancletas",
    "flip flop",
    "ojota",
    "ojotas",
    "slide",
    "slides",
  ],
  deportivos: [
    "deportivo",
    "deportivos",
    "running",
    "runners",
    "training",
    "gym",
    "air max",
    "air force",
    "jordan",
    "yeezy",
    "boost",
    "crossfit",
    "futbol",
    "fútbol",
    "soccer cleats",
    "tacos",
  ],
  accesorios: [
    "cinturon",
    "cinturón",
    "correa",
    "gorra",
    "gorras",
    "cap",
    "snapback",
    "bufanda",
    "guantes",
    "cartera",
    "billetera",
    "bolso",
    "morral",
    "mochila",
    "cartera",
    "banco",
    "pañuelo",
    "medias",
    "calcetines",
    "sombrero",
    "lentes de sol",
    "gafas de sol",
  ],
};

/** Más específico gana en empate (calzado genérico al final). */
export const ROPA_MODA_CATEGORY_PRIORITY: Record<string, number> = {
  botas: 1,
  sandalias: 2,
  zapatos: 3,
  deportivos: 4,
  camisas: 5,
  pantalones: 6,
  calzado: 7,
  accesorios: 8,
};
