/** Diccionario local — Ropa, Calzado y Moda (departamentos / audiencia). */

export const ROPA_MODA_CATEGORY_KEYWORDS: Record<string, string[]> = {
  damas: [
    "dama",
    "damas",
    "mujer",
    "mujeres",
    "lady",
    "ladies",
    "femenino",
    "femenina",
    "para ella",
    "women",
    "woman",
  ],
  caballeros: [
    "caballero",
    "caballeros",
    "hombre",
    "hombres",
    "masculino",
    "para el",
    "para él",
    "men",
    "man",
    "gents",
  ],
  ninos: [
    "nino",
    "niño",
    "ninos",
    "niños",
    "nina",
    "niña",
    "ninas",
    "niñas",
    "kids",
    "kid",
    "infantil",
    "bebes",
    "bebés",
    "baby",
    "junior",
  ],
  unisex: ["unisex", "uni sex", "para todos", "mixta", "mixto"],
  accesorios: [
    "cinturon",
    "cinturón",
    "correa",
    "gorra",
    "gorras",
    "cap",
    "snapback",
    "bufanda",
    "guantes",
    "cartera",
    "billetera",
    "bolso",
    "morral",
    "mochila",
    "pañuelo",
    "medias",
    "calcetines",
    "sombrero",
    "lentes de sol",
    "gafas de sol",
    "accesorio",
    "accesorios",
  ],
};

/** Más específico gana en empate. */
export const ROPA_MODA_CATEGORY_PRIORITY: Record<string, number> = {
  damas: 1,
  caballeros: 2,
  ninos: 3,
  unisex: 4,
  accesorios: 5,
};
