/** Diccionario local — Salud, Belleza y Cuidado Personal */

export const SALUD_BELLEZA_CATEGORY_KEYWORDS: Record<string, string[]> = {
  "cuidado-personal": [
    "serum",
    "sérum",
    "crema",
    "crema hidratante",
    "hidratante",
    "protector solar",
    "spf",
    "bloqueador",
    "sunscreen",
    "limpiador facial",
    "cleanser",
    "tonico",
    "tónico",
    "exfoliante",
    "contorno de ojos",
    "mascarilla facial",
    "face mask",
    "after shave",
    "desodorante",
    "jabon",
    "jabón",
    "gel de ducha",
    "body lotion",
    "locion corporal",
    "loción corporal",
  ],
  maquillaje: [
    "maquillaje",
    "makeup",
    "labial",
    "lipstick",
    "gloss",
    "rubor",
    "blush",
    "base",
    "base de maquillaje",
    "foundation",
    "corrector",
    "concealer",
    "mascara",
    "máscara de pestañas",
    "delineador",
    "eyeliner",
    "sombras",
    "sombra",
    "palette",
    "paleta",
    "polvo compacto",
    "primer",
    "setting spray",
  ],
  fragancias: [
    "perfume",
    "perfumes",
    "fragancia",
    "fragancias",
    "colonia",
    "eau de toilette",
    "eau de parfum",
    "edt",
    "edp",
    "body mist",
    "splash",
  ],
  suplementos: [
    "suplemento",
    "suplementos",
    "vitamina",
    "vitaminas",
    "multivitamin",
    "proteina",
    "proteína",
    "whey",
    "creatina",
    "omega",
    "colageno",
    "colágeno",
    "magnesio",
    "zinc",
    "bcaa",
    "pre workout",
    "pre-workout",
  ],
  cabello: [
    "shampoo",
    "champu",
    "champú",
    "acondicionador",
    "conditioner",
    "tinte",
    "tintura",
    "coloracion",
    "coloración",
    "tratamiento capilar",
    "keratina",
    "aceite capilar",
    "hair oil",
    "gel capilar",
    "cera capilar",
    "leave in",
    "anticaida",
    "anticaída",
  ],
};

export const SALUD_BELLEZA_CATEGORY_PRIORITY: Record<string, number> = {
  maquillaje: 1,
  fragancias: 2,
  cabello: 3,
  "cuidado-personal": 4,
  suplementos: 5,
};
