/* eslint-disable */
// Generated by scripts/generate-assistant-avatars.mjs — do not edit manually.

import type { StoreRubro } from "@/src/config/categories";

export type AssistantAvatarAnimationKind = ["float","wave","glow","pulse","bob"][number];

export type AssistantAvatarRubro = StoreRubro;

export interface AssistantAvatarPresetManifestEntry {
  id: string;
  label: string;
  rubro: AssistantAvatarRubro;
  imagePath: string;
  animation: AssistantAvatarAnimationKind;
}

export const ASSISTANT_AVATAR_RUBRO_LABELS: Record<AssistantAvatarRubro, string> = {
  "tecnologia": "Tecnología y Electrónica",
  "coleccionables": "Coleccionables y Cómics",
  "ropa-moda": "Ropa, Calzado y Moda",
  "alimentos": "Alimentos y Bebidas",
  "salud-belleza": "Salud, Belleza y Cuidado",
  "papeleria-libreria-oficina": "Papelería, Librería y Oficina"
} as Record<AssistantAvatarRubro, string>;

export const ASSISTANT_AVATAR_PRESET_MANIFEST: AssistantAvatarPresetManifestEntry[] = [
  {
    "id": "tecnologia-robbo",
    "label": "Robbo el Robot",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-robbo.svg",
    "animation": "bob"
  },
  {
    "id": "tecnologia-cctv",
    "label": "Cámara Vigilante",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-cctv.svg",
    "animation": "wave"
  },
  {
    "id": "tecnologia-nerd",
    "label": "Nerd Techie",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-nerd.svg",
    "animation": "float"
  },
  {
    "id": "tecnologia-drone",
    "label": "Dron Amigo",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-drone.svg",
    "animation": "bob"
  },
  {
    "id": "tecnologia-chipster",
    "label": "Chipster",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-chipster.svg",
    "animation": "glow"
  },
  {
    "id": "tecnologia-laptop-guru",
    "label": "Gurú Laptop",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-laptop-guru.svg",
    "animation": "pulse"
  },
  {
    "id": "tecnologia-vr-buddy",
    "label": "VR Buddy",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-vr-buddy.svg",
    "animation": "float"
  },
  {
    "id": "tecnologia-console-pal",
    "label": "Control Gamer",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-console-pal.svg",
    "animation": "wave"
  },
  {
    "id": "tecnologia-satellite",
    "label": "Satélite Soli",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-satellite.svg",
    "animation": "bob"
  },
  {
    "id": "tecnologia-wire-bot",
    "label": "Bot Cableado",
    "rubro": "tecnologia",
    "imagePath": "/assistant-avatars/tecnologia-wire-bot.svg",
    "animation": "pulse"
  },
  {
    "id": "coleccionables-neo",
    "label": "Neo Anime",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-neo.svg",
    "animation": "float"
  },
  {
    "id": "coleccionables-sakura",
    "label": "Sakura Kawaii",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-sakura.svg",
    "animation": "glow"
  },
  {
    "id": "coleccionables-hero",
    "label": "Héroe Manga",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-hero.svg",
    "animation": "wave"
  },
  {
    "id": "coleccionables-ninja",
    "label": "Ninja Shadow",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-ninja.svg",
    "animation": "bob"
  },
  {
    "id": "coleccionables-wizard",
    "label": "Mago Arcano",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-wizard.svg",
    "animation": "glow"
  },
  {
    "id": "coleccionables-mecha",
    "label": "Mecha Pilot",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-mecha.svg",
    "animation": "pulse"
  },
  {
    "id": "coleccionables-chibi",
    "label": "Chibi Star",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-chibi.svg",
    "animation": "float"
  },
  {
    "id": "coleccionables-dragon",
    "label": "Dragon Keeper",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-dragon.svg",
    "animation": "bob"
  },
  {
    "id": "coleccionables-comic",
    "label": "Comic Boom",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-comic.svg",
    "animation": "wave"
  },
  {
    "id": "coleccionables-mask",
    "label": "Máscara Heroica",
    "rubro": "coleccionables",
    "imagePath": "/assistant-avatars/coleccionables-mask.svg",
    "animation": "pulse"
  },
  {
    "id": "ropa-moda-chic",
    "label": "Estilista Chic",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-chic.svg",
    "animation": "float"
  },
  {
    "id": "ropa-moda-glam",
    "label": "Glam Boutique",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-glam.svg",
    "animation": "glow"
  },
  {
    "id": "ropa-moda-runway",
    "label": "Runway Star",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-runway.svg",
    "animation": "wave"
  },
  {
    "id": "ropa-moda-vintage",
    "label": "Vintage Soul",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-vintage.svg",
    "animation": "bob"
  },
  {
    "id": "ropa-moda-street",
    "label": "Street Trend",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-street.svg",
    "animation": "pulse"
  },
  {
    "id": "ropa-moda-minimal",
    "label": "Minimal Lux",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-minimal.svg",
    "animation": "float"
  },
  {
    "id": "ropa-moda-luxe",
    "label": "Luxe Maison",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-luxe.svg",
    "animation": "glow"
  },
  {
    "id": "ropa-moda-boutique",
    "label": "Boutique Pro",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-boutique.svg",
    "animation": "wave"
  },
  {
    "id": "ropa-moda-stylist",
    "label": "Stylist Pro",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-stylist.svg",
    "animation": "bob"
  },
  {
    "id": "ropa-moda-trend",
    "label": "Trend Setter",
    "rubro": "ropa-moda",
    "imagePath": "/assistant-avatars/ropa-moda-trend.svg",
    "animation": "pulse"
  },
  {
    "id": "alimentos-toro",
    "label": "Toro Emblema",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-toro.svg",
    "animation": "pulse"
  },
  {
    "id": "alimentos-vaca",
    "label": "Vaca Amigable",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-vaca.svg",
    "animation": "bob"
  },
  {
    "id": "alimentos-cabra",
    "label": "Cabra Campestre",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-cabra.svg",
    "animation": "wave"
  },
  {
    "id": "alimentos-burger",
    "label": "Burger Premium",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-burger.svg",
    "animation": "float"
  },
  {
    "id": "alimentos-helado",
    "label": "Cono Kawaii",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-helado.svg",
    "animation": "glow"
  },
  {
    "id": "alimentos-pizza",
    "label": "Pizza Animada",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-pizza.svg",
    "animation": "bob"
  },
  {
    "id": "alimentos-chef",
    "label": "Chef Maestro",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-chef.svg",
    "animation": "wave"
  },
  {
    "id": "alimentos-barista",
    "label": "Barista Pro",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-barista.svg",
    "animation": "glow"
  },
  {
    "id": "alimentos-uvas",
    "label": "Racimo Premium",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-uvas.svg",
    "animation": "float"
  },
  {
    "id": "alimentos-palta",
    "label": "Palta Sonriente",
    "rubro": "alimentos",
    "imagePath": "/assistant-avatars/alimentos-palta.svg",
    "animation": "pulse"
  },
  {
    "id": "salud-belleza-spa",
    "label": "Spa Serenity",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-spa.svg",
    "animation": "bob"
  },
  {
    "id": "salud-belleza-serum",
    "label": "Serum Lab",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-serum.svg",
    "animation": "pulse"
  },
  {
    "id": "salud-belleza-bloom",
    "label": "Bloom Care",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-bloom.svg",
    "animation": "wave"
  },
  {
    "id": "salud-belleza-care",
    "label": "Care Expert",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-care.svg",
    "animation": "float"
  },
  {
    "id": "salud-belleza-mint",
    "label": "Mint Fresh",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-mint.svg",
    "animation": "bob"
  },
  {
    "id": "salud-belleza-pearl",
    "label": "Pearl Elegance",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-pearl.svg",
    "animation": "glow"
  },
  {
    "id": "salud-belleza-leaf",
    "label": "Bienestar Natural",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-leaf.svg",
    "animation": "float"
  },
  {
    "id": "salud-belleza-glow",
    "label": "Glow Beauty",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-glow.svg",
    "animation": "glow"
  },
  {
    "id": "salud-belleza-zen",
    "label": "Zen Balance",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-zen.svg",
    "animation": "pulse"
  },
  {
    "id": "salud-belleza-radiance",
    "label": "Radiance Pro",
    "rubro": "salud-belleza",
    "imagePath": "/assistant-avatars/salud-belleza-radiance.svg",
    "animation": "wave"
  },
  {
    "id": "papeleria-libreria-oficina-pen",
    "label": "Asistente de Oficina",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-pen.svg",
    "animation": "wave"
  },
  {
    "id": "papeleria-libreria-oficina-book",
    "label": "Book Expert",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-book.svg",
    "animation": "bob"
  },
  {
    "id": "papeleria-libreria-oficina-desk",
    "label": "Desk Pro",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-desk.svg",
    "animation": "pulse"
  },
  {
    "id": "papeleria-libreria-oficina-planner",
    "label": "Planner Ace",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-planner.svg",
    "animation": "glow"
  },
  {
    "id": "papeleria-libreria-oficina-archive",
    "label": "Archive Keeper",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-archive.svg",
    "animation": "float"
  },
  {
    "id": "papeleria-libreria-oficina-pencil",
    "label": "Pencil Sketch",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-pencil.svg",
    "animation": "wave"
  },
  {
    "id": "papeleria-libreria-oficina-folder",
    "label": "Folder Master",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-folder.svg",
    "animation": "bob"
  },
  {
    "id": "papeleria-libreria-oficina-ink",
    "label": "Ink Studio",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-ink.svg",
    "animation": "glow"
  },
  {
    "id": "papeleria-libreria-oficina-note",
    "label": "Notas Útiles",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-note.svg",
    "animation": "float"
  },
  {
    "id": "papeleria-libreria-oficina-stamp",
    "label": "Stamp Official",
    "rubro": "papeleria-libreria-oficina",
    "imagePath": "/assistant-avatars/papeleria-libreria-oficina-stamp.svg",
    "animation": "pulse"
  }
];
